services:
  postgres:
    image: postgres:17.2
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${PG_NAME:-postgres}
      POSTGRES_USER: ${PG_USER:-root}
      POSTGRES_PASSWORD: ${PG_PASSWORD:-1234}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -h postgres -p 5432" ]
      interval: 3s
      timeout: 3s
      retries: 10

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgres://root:1234@postgres:5432/postgres
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8000:8000"
#  frontend:
#    build: ./frontend
#    expose: [ 3000 ]
#    restart: unless-stopped
#    init: true
#    env_file:
#      - ./frontend/.env
#    ports:
#      - 443:443
#      - 80:80
#    volumes:
#      - caddy_data:/data
#      - caddy_config:/config
#
#volumes:
#  caddy_data:
#  caddy_config:
#  static:

